<a href="https://colab.research.google.com/github/TanZz9/LearnPyTorch/blob/main/0_LearnPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

In [ ]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.1
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.14.0
backcall                         0.2.0
beautifulsoup4                   4.11.2
bidict                           0.22.1
b

In [ ]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.1.0+cu121


### introduction to tensor
#### creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
print(vector, vector.ndim, vector.shape)

tensor([7, 7]) 1 torch.Size([2])


In [ ]:
# MATRIX
matrix = torch.tensor([[1, 1],
                       [2, 2]])
matrix

tensor([[1, 1],
        [2, 2]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.arange(24).reshape(2, 3, 4)
TENSOR

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
print(TENSOR.shape, TENSOR.ndim)

torch.Size([2, 3, 4]) 3


In [ ]:
TENSOR[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
tensor = TENSOR.reshape(1,1,24)
print(tensor, tensor.ndim)

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
          17, 18, 19, 20, 21, 22, 23]]]) 3


#### Random Tensors


In [ ]:
# create a random tensor of size(3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6863, 0.0924, 0.0285, 0.7881],
        [0.7567, 0.4389, 0.8604, 0.1598],
        [0.0951, 0.4266, 0.5977, 0.5495]])

In [ ]:
# Create a random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, length, color channel
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [ ]:
random_image_size_tensor

tensor([[[0.9069, 0.0150, 0.9837],
         [0.3877, 0.3711, 0.3949],
         [0.6391, 0.7021, 0.9747],
         ...,
         [0.9003, 0.4298, 0.7880],
         [0.7247, 0.6371, 0.1638],
         [0.4263, 0.5280, 0.2177]],

        [[0.6230, 0.1748, 0.7910],
         [0.2116, 0.9120, 0.7185],
         [0.5310, 0.1163, 0.3092],
         ...,
         [0.7938, 0.2488, 0.1304],
         [0.1213, 0.8343, 0.1564],
         [0.5584, 0.5664, 0.4029]],

        [[0.3009, 0.4584, 0.0123],
         [0.0467, 0.7966, 0.2861],
         [0.1569, 0.3323, 0.3012],
         ...,
         [0.0040, 0.9084, 0.1632],
         [0.1175, 0.0599, 0.1496],
         [0.8259, 0.3185, 0.3766]],

        ...,

        [[0.2982, 0.1443, 0.6974],
         [0.7368, 0.1291, 0.0283],
         [0.4773, 0.0122, 0.9315],
         ...,
         [0.0855, 0.5457, 0.4685],
         [0.0214, 0.3498, 0.1140],
         [0.0607, 0.8196, 0.5858]],

        [[0.8984, 0.4827, 0.6694],
         [0.1150, 0.8036, 0.0031],
         [0.

#### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3, 4))
ones = torch.ones(size=(3, 4), dtype=int)
ones, zeros

(tensor([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

#### A range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor datatype
**Note:** 3 big errors I'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.arange(10, dtype=torch.float32)
float_32_tensor.dtype

torch.float32

#### Get information from tensor


In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6825, 0.8792, 0.0720, 0.0770],
        [0.4101, 0.5791, 0.0148, 0.7838],
        [0.3878, 0.1847, 0.4387, 0.7508]])

In [ ]:
some_tensor.dtype, some_tensor.shape, some_tensor.size(), some_tensor.device

(torch.float32, torch.Size([3, 4]), torch.Size([3, 4]), device(type='cpu'))

### Manipulate Tensors

In [ ]:
%%time
tensor = torch.arange(9).reshape(3, 3)
print(f"Matrix multiplication: {tensor}\n * {tensor}\n equals to \n{torch.matmul(tensor, tensor)}")

Matrix multiplication: tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
 * tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
 equals to 
tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])
CPU times: user 3.65 ms, sys: 35 µs, total: 3.69 ms
Wall time: 3.1 ms


### Finding the min, max, mean, sum, etc(tensor aggregation)

In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x), x.min() #Find the min

(tensor(0), tensor(0))

In [ ]:
torch.max(x), x.max() #Find the max

(tensor(90), tensor(90))

In [ ]:
x.type(torch.float32).mean().item() # you should transfer the int to a higher type which may bring more accuracy and flexibility

45.0

In [ ]:
torch.sum(x), x.dtype, x.sum()

(tensor(450), torch.int64, tensor(450))

##### Find the positional min and max

In [ ]:
#Find the index of a tensor that has the minimum/maxmun value
x.argmin(), torch.argmin(x, dim = 0)

(tensor(0), tensor(0))

In [ ]:
x.argmax()

tensor(9)

In [ ]:
Matrix = torch.arange(12).reshape(3,4)
Matrix.argmin(dim=1, keepdim=True)

tensor([[0],
        [0],
        [0]])

### Reshaping, stacking, squeezing and unsqueezing the tensors
* reshape - reshape an input tensor to a defined shape
* view - return a view of an input tensor of certain but keep the memory as the original tensor
* stack - combine multiple tensors on top of each other(vstack) or side by side(hstack)
* squeeze - remove all 1 dimensions from a tensor
* unsqueeze - add a 1 dimension to a target tensor
* Permute - return a view of the input with dimension permuted(swapped) in a certain way

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshape = x.reshape(1, 9)
x_reshape, id(x_reshape) == id(x)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), False)

In [ ]:
x_view = x.view(1, 9)
x_view, id(x_view) == id(x)

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), False)

In [ ]:
x_view[:, 0] = 5
x_view, x, id(x), id(x_view)

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 135153130082032,
 135153243603008)

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked, x_stacked.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.],
         [1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2, 1)
x.size()

torch.Size([2, 1, 2, 1, 2, 1])

In [ ]:
y = torch.squeeze(x)
y.shape

torch.Size([2, 2, 2])

In [ ]:
y = torch.squeeze(x, (1, 2, 3))
y.size()

torch.Size([2, 2, 2, 1])

In [ ]:
z = x.unsqueeze(dim=0)
z.shape, z

(torch.Size([1, 2, 1, 2, 1, 2, 1]),
 tensor([[[[[[[0.],
              [0.]]],
 
 
            [[[0.],
              [0.]]]]],
 
 
 
 
          [[[[[0.],
              [0.]]],
 
 
            [[[0.],
              [0.]]]]]]]))

In [ ]:
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [ ]:
 y = x.permute(2, 0, 1)
 y  # they shared the same memory

tensor([[[-0.5194, -0.2409,  1.2715],
         [-1.2497, -0.1895,  0.6943]],

        [[ 0.2871, -0.4639,  1.2924],
         [-0.5801,  2.4653,  0.3046]],

        [[-0.4333, -1.0115, -0.7925],
         [-2.0217, -1.1565, -1.1877]],

        [[-0.5231,  0.5100,  0.0883],
         [ 0.1816,  0.3649, -0.8140]],

        [[-0.2816, -0.1187,  0.4737],
         [ 0.2441, -0.5268, -2.2647]]])

In [ ]:
x = torch.arange(1, 13).reshape(1, 3, 4)
x[0, 1]

tensor([5, 6, 7, 8])

In [ ]:
x[0, 2, :]

tensor([ 9, 10, 11, 12])

### PyTorch tensors & Numpy
Numpy is a popular scientific Python numerical cpmputing library.
And beacuse of this, PyTorch has functionality to interact with numpy.
* Data in Numpy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> Numpy -> torch.Tensor.numpy()

Warining: Default datatype: numpy: float64
                            tensor: float32

In [ ]:
import numpy as np

array = np.arange(1., 8.)
tensor = torch.from_numpy(array).type(torch.float32) # Warning: the default type is float46!!!
array, tensor, tensor.dtype


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

### Reproducibility

In [ ]:
# Make some random but reproducible tensors
RANDOM_SEAD = 1234

torch.manual_seed(RANDOM_SEAD)
random_tensor_A = torch.randn(3, 4)
torch.manual_seed(RANDOM_SEAD)
random_tensor_B = torch.randn(3, 4)

random_tensor_A == random_tensor_B


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Using GPU

In [ ]:
!nvidia-smi

Sat Jan  6 10:19:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
# count number of device
torch.cuda.device_count()

1

In [ ]:
# putting the tensors or the models on the GPU
tensor = torch.tensor([1, 2, 3])
print(tensor.device)  # default device is "CPU"


cpu


In [ ]:
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

tensor([1, 2, 3], device='cuda:0')

In [ ]:
# moving the tensor back to the CPU
# if tensor is on the GPU, it can not transfer to numpy
tensor_on_GPU.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
tensor_back_on_cpu = tensor_on_GPU.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])