<a href="https://colab.research.google.com/github/TanZz9/LearnPyTorch/blob/main/LearnPyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## PyTorch Fundamentals

In [ ]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.1
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.3.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array-record                     0.5.0
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.0
attrs                            23.1.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.14.0
backcall                         0.2.0
beautifulsoup4                   4.11.2
bidict                           0.22.1
b

In [ ]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.1.0+cu121


### introduction to tensor
#### creating tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# get tensor back as python int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7, 7])
print(vector, vector.ndim, vector.shape)

tensor([7, 7]) 1 torch.Size([2])


In [ ]:
# MATRIX
matrix = torch.tensor([[1, 1],
                       [2, 2]])
matrix

tensor([[1, 1],
        [2, 2]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.arange(24).reshape(2, 3, 4)
TENSOR

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
print(TENSOR.shape, TENSOR.ndim)

torch.Size([2, 3, 4]) 3


In [ ]:
TENSOR[0]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
tensor = TENSOR.reshape(1,1,24)
print(tensor, tensor.ndim)

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
          17, 18, 19, 20, 21, 22, 23]]]) 3


#### Random Tensors


In [ ]:
# create a random tensor of size(3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6863, 0.0924, 0.0285, 0.7881],
        [0.7567, 0.4389, 0.8604, 0.1598],
        [0.0951, 0.4266, 0.5977, 0.5495]])

In [ ]:
# Create a random tensor with similar shape to a image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, length, color channel
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [ ]:
random_image_size_tensor

tensor([[[0.9069, 0.0150, 0.9837],
         [0.3877, 0.3711, 0.3949],
         [0.6391, 0.7021, 0.9747],
         ...,
         [0.9003, 0.4298, 0.7880],
         [0.7247, 0.6371, 0.1638],
         [0.4263, 0.5280, 0.2177]],

        [[0.6230, 0.1748, 0.7910],
         [0.2116, 0.9120, 0.7185],
         [0.5310, 0.1163, 0.3092],
         ...,
         [0.7938, 0.2488, 0.1304],
         [0.1213, 0.8343, 0.1564],
         [0.5584, 0.5664, 0.4029]],

        [[0.3009, 0.4584, 0.0123],
         [0.0467, 0.7966, 0.2861],
         [0.1569, 0.3323, 0.3012],
         ...,
         [0.0040, 0.9084, 0.1632],
         [0.1175, 0.0599, 0.1496],
         [0.8259, 0.3185, 0.3766]],

        ...,

        [[0.2982, 0.1443, 0.6974],
         [0.7368, 0.1291, 0.0283],
         [0.4773, 0.0122, 0.9315],
         ...,
         [0.0855, 0.5457, 0.4685],
         [0.0214, 0.3498, 0.1140],
         [0.0607, 0.8196, 0.5858]],

        [[0.8984, 0.4827, 0.6694],
         [0.1150, 0.8036, 0.0031],
         [0.

#### Zeros and Ones

In [ ]:
zeros = torch.zeros(size=(3, 4))
ones = torch.ones(size=(3, 4), dtype=int)
ones, zeros

(tensor([[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

#### A range of tensors and tensors-like

In [ ]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor datatype
**Note:** 3 big errors I'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.arange(10, dtype=torch.float32)
float_32_tensor.dtype

torch.float32

#### Get information from tensor


In [ ]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6825, 0.8792, 0.0720, 0.0770],
        [0.4101, 0.5791, 0.0148, 0.7838],
        [0.3878, 0.1847, 0.4387, 0.7508]])

In [ ]:
some_tensor.dtype, some_tensor.shape, some_tensor.size(), some_tensor.device

(torch.float32, torch.Size([3, 4]), torch.Size([3, 4]), device(type='cpu'))

### Manipulate Tensors

In [ ]:
%%time
tensor = torch.arange(9).reshape(3, 3)
print(f"Matrix multiplication: {tensor}\n * {tensor}\n equals to \n{torch.matmul(tensor, tensor)}")

Matrix multiplication: tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
 * tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
 equals to 
tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])
CPU times: user 3.65 ms, sys: 35 µs, total: 3.69 ms
Wall time: 3.1 ms
